### PR TITLE
Adds configurable attention check module and fix some post-playtest bugs.

### LINKED ISSUE #177: Add custom Prolific codes for different cases

### PR DESCRIPTION
**Pull request by cjqian**
Fixes #177 #190 #187

### CODE REVIEW

File: lit/src/app.ts [hunk 1]
```diff
@@ -92,11 +92,15 @@ export class App extends MobxLitElement {
       case Pages.PARTICIPANT:
         return this.renderParticipantView(this.renderParticipant());
       case Pages.PARTICIPANT_STAGE:
-        // TODO: Ignore this for experimenters, and allow experimenters to add this.
-        if (false) {
+        if (
+          !this.authService.isExperimenter &&
```
Comment (vivtsai) [inline lit/src/app.ts:96]: What do you think about verifying "isExperimenter" (and maybe the attention check params?) inside the attention-check-popup component (so that it's not possible to render it for experimenters viewing things)? Just to specifically safeguard the popup against experimenters in preview mode (since we could use it in other locations later).

Comment (vivtsai) [reply lit/src/app.ts:96]: We can follow up with this refactor though!

Comment (cjqian) [reply lit/src/app.ts:96]: Done!
